name: On Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  update_documentation:
    name: Updating documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt

      - name: Building documentation
        run: |
          cd docs && make clean && make html

    - name: Publishing documentation
      run: |
        ghp-import -f -n -c docs.jointakahe.org -p docs/build/html
